### ISSUE TITLE
SVG animations intermittently stall out on safari

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#492]
Not seeing any error in web inspector.

**Comment by ofsound** [comment]
@sudara 

Have you seen animation bugs or SVGs stalling out recently in specifically Safari?

The only SVG bug i recall seeing recently on alonetone.com is #552
where you can get this incomplete version of the loading animation

Maybe some others that qualified for this were fixed by re-writing the main play/pause animation

I feel like I haven't seen a fav or follow misfire recently...

Just wondering if we can close this issue, and re-open specific cases if they happen?

**Comment by sudara** [comment]
This is still happening to me on Safari, seems like a framerate issue. It tends to stall right when the loading is finishing, sorta click-click-click-click and then triggers the transition to the pause.

**Comment by sudara** [comment]
Dupe of #724
